apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.ContainerRegistryCredentials }}
kind: Secret
metadata:
  name: container-registry-credentials
  namespace: my-namespace
type: kubernetes.io/dockerconfigjson