apiVersion: v1
data:
  .dockerconfigjson: {{ required "A valid .Values.ContainerRegistryCredentials required!" .Values.ContainerRegistryCredentials }}
kind: Secret
metadata:
  name: container-registry-credentials
  namespace: my-namespace
type: kubernetes.io/dockerconfigjson