apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend
  namespace: my-namespace
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: {{ .Values.ingress.hosts.frontend }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: website-clusterip-svc
            port: 
              number: 8000
